spring.application.name=ms-security
server.port=8081


spring.mongodb.uri=mongodb+srv://andresgantivar38547_db_user:joanelpinga@cluster0.d1h9gql.mongodb.net/?appName=Cluster0
spring.mongodb.database=db_security
jwt.secret=aaa
jwt.expiration=3600000